cockpit-project/cockpit-ostree

README.md
To be more in line with Cockpit's release notes and general terminology.
=> README: Replace "component" with "page"

README.md
Please don't merge - I want to use this to test running the tests in CI.
=> README: Fix overly long line

Makefile, cockpit-ostree.spec.in
https://bugzilla.redhat.com/show_bug.cgi?id=1731687
=> spec: Depend on package instead of file path

.tasks
There are currently no pending npm updates (I bumped them all yesterday), but PR #39 was a manual run that demonstrated that this works.
=> Add .tasks to regularly update npm modules

.gitignore, Makefile
I did demo run on my forks:
Updated source: https://github.com/marusak/cockpit-ostree-weblate/commit/562b455de0699369c38ffece84bedd3cf5a597d8
Pull request: https://github.com/marusak/cockpit-ostree/pull/1
We don't have yet Weblate project as I don't have permissions to create one. But I sent request for it.
(p.s. We don't have no-test label) EDIT: We do now :)
=> Add translations

src/app.js, src/remotes.js
This is another prerequisite for porting to React.
=> Confine Angular usage to app.js, separate ostree remote logic

src/app.jsx, src/remotes.js
Baby steps to split apart #114.
=> app, remotes: Use standard JS Promise API

src/client.js
Keep cockpit.defer() for run_transaction() as that uses progress
notify.
connect() will be ported separately as that is very complex.
=> client: Convert some jQuery to JS Promises

package.json
See https://github.com/react-dropzone/react-dropzone/issues/1022
=> package.json: Add 'file-selector' dependency

src/app.jsx
Blocked on:
Addresses https://github.com/cockpit-project/cockpit/issues/15573
=> pf4: Use SVG spinner to fix direction and glitches

cockpit-ostree.spec.in, test/check-ostree, test/rpmbuild-local, test/vm.install
Both rhel-atomic and continuous atomic are not a thing anymore.
=> Cleanup unnecessary rhel cases

Makefile, README.md, cockpituous-release, src/app.jsx
Also update the weblate repo reference to `main`
=> various: master → main updates

src/app.jsx, test/check-ostree
This is just very coarse for now, but better than a broken page.
=> React to superuser changes

Makefile
"cockpit-" prefix was duplicated.
=> Makefile: Fix name of node cache tarball

test/check-ostree
Let's make this string formatting method the only one to use from now
on.
These files were autoconverted with flynt.
=>  tests: autoconvert all python string formatting to fstring

cockpituous-release
Point 13 on https://fedorapeople.org/groups/schedule/f-36/f-36-key-tasks.html
=> cockpituous: Enable bodhi for Fedora 36

src/app.jsx, src/changeRemoteModal.jsx, src/index.html, src/manifest.json, test/check-ostree
Fixes https://github.com/cockpit-project/cockpit-ostree/issues/319
=> Use sentence case

.github/codeql-config.yml, .github/workflows/codeql.yml, src/app.jsx, src/index.html
This makes ostree 100% green \o/
=> Add Github code scanning workflow

.eslintrc.json, package.json
All our other projects enable this plugin to spot accessibility issues in JSX.
=> eslint: enable jsx-a11y plugin

src/deploymentModals.jsx, src/ostree.jsx
Change title in Clean up modal.
Fix OSTree spelling.
=> Fix titles

.gitignore
Follow how all our other projects format their gitignore file.
=> .gitignore: update gitignore from starter-kit

src/ostree.scss
This was resolved in https://github.com/patternfly/patternfly-react/pull/5744
---
Manually verified, but hopefully pixel tests also cover it :)
=> Drop old PF table actions override

src/ostree.scss
A bit of procastination as my other PR fails with pixel tests for RTL, so let's see if this one "flakes" or "fails" as well.
https://cockpit-logs.us-east-1.linodeobjects.com/pull-541-6cfb7af5-20240314-095647-fedora-coreos/log.html
=> Cleanup scss

src/client.js, test/check-ostree
=> Drop cockpit.defer() API in favor of async and Promise

.github/workflows/tasks-container-update.yml
See https://github.com/cockpit-project/cockpit-ostree/actions/runs/8502918141/job/23287717809
Same copy pasta as in https://github.com/cockpit-project/cockpit-certificates/pull/286
=> workflows: Fix safe directory path in tasks-container-update.yml, fix container image

Makefile, test/vm.install
See commit messages for details. This is some preparation for testing bootc.
=> test: Unpack rpm into /usr/local/

pyproject.toml, test/check-ostree
This doesn't do much yet, but gives us something to build on.
=> Initial test setup on centos-9-bootc

Makefile, test/check-ostree
See https://github.com/cockpit-project/cockpit/pull/20563
=> test: Adjust to changed key input testlib API

package.json
=> package.json: Drop sizzle

.github/dependabot.yml
Copied from our other projects.
---
Avoids things like #723
=> dependabot: Ignore major PatternFly and sass updates

src/ostree.scss
cockpit-ws now serves the new font which comes with PatternFly 6.
=> test: update pixel tests for cockpit-ws 337
