cockpituous-release
Also fix `RELEASE_SPEC`, it still had the starter-kit default.
---
I tested this with cockpituous' release-runner in dry-run mode:
```
❱❱❱ ~/upstream/cockpituous/release/release-runner -n -t 173 ./cockpituous-release 
> Starting: release-source
> Committing first tarball
> Done: release-source
> Starting: release-srpm
> Updating spec file
> Copying sources
> Building SRPM
> Done: release-srpm
> Starting: release-github
> Creating release draft: 173
> Uploading file: _release/source/cockpit-ostree-173.tar.gz
############################################################################################################################################################ 100,0%
> Ready: release-github
> Starting: release-copr @cockpit/cockpit-preview
> Validating ~/.config/copr
release-copr: …
```
=> cockpituous: Enable github and COPR releases

test/vm.install
Occasionally the VM install fails like this:
```
+ atomic run cockpit/ws
The image 'ws' appears to have not been installed and has an INSTALL label.  You should install this image first.  Re-run with --ignore to bypass this error.
Command '/var/tmp/vm.install' returned non-zero exit status 1.
```
We do run `atomic install`, this seems to be a race condition in Fedora
Atomic. Skip that check, we are not testing `atomic` itself here.
=> test: Force running ws container

test/check-ostree
The current rhel-atomic now also picked up the new rpm-ostree with the
changed rollback behaviour.
See https://github.com/cockpit-project/cockpit/pull/9743
=> test: Adjust Ostree tests for new rpm-ostree on rhel-atomic

cockpit-ostree.spec.in
- Entirely drop `%build` section, as there is nothing to do anyway.
- Use `%make_install` macro.
- Replace the complicated file list wrangling with a simple directory
enumeration.
Thanks to Igor Gnatenko for the suggestions!
See https://bugzilla.redhat.com/show_bug.cgi?id=1603146
=> Simplify spec file

Makefile, cockpit-ostree.spec.in
Hardcode the package name instead of parsing it from package.json. It
won't change for cockpit-ostree, this was a leftover from starter-kit.
=> Drop python3 build requirement

test/vm.install
This is workaround for https://github.com/projectatomic/atomic/issues/1258
=> test: Set up atomic /var/lib path

cockpit-ostree.spec.in
They are large and just for debugging. If they are ever needed, they
should move into a separate -debugsource package, but this seems a bit
overkill here.
This reduces the rpm from 680 to 180 kB.
=> Drop source map

package.json
This also updates to a newer js-yaml, which addresses the current two
`npm audit` issues:
- https://npmjs.com/advisories/788
- https://npmjs.com/advisories/813
=> Bump css-loader to current version

packit.yaml
See <https://packit.dev>. This will gradually replace our cockpituous
configuration.
=> Add packit configuration

package.json
See https://github.com/less/less.js/issues/3414
No breaking changes for us were introduced. Also inspected that less is loaded correctly.
=> package.json: Bump version of less-loader

.eslintrc.json
Eslint shimmies up directories looking for more eslintrcs. As
make-checkout now clones projects in a subdirectory, this can result in
some strange interactions.
https://eslint.org/docs/user-guide/configuring
=> eslintrc: Set "root" to true [no-test]

src/ostree.less
less ≥ 3.11 will try to look for a <filename>.less (e. g.
"page.css.less") which does not exist.
=> Drop less markers from *.css imports

test/check-ostree
The error now says "public key not found" instead of "none are in
trusted keyring". Accept either now.
=> test: Adjust expected error message for new Fedora CoreOS

test/check-ostree
This ignores the sudo journal messages, and thus fixes running against
Cockpit 219.
=> test: Allow authorize messages

Makefile, test/rpmbuild-local, test/rpmbuild-vm
Binary rpms (even `noarch`) built on Fedora ≥ 31 cannot be installed any
more into continuous-atomic's rpm-ostree, due to an RPM format change.
When testing continuous-atomic, build the srpm inside a centos-7 image.
Add a test/rpmbuild-vm script for that.
For symmetry, move the call for local rpm builds out into
test/rpmbuild-local, and use the srpm as well instead of the .spec.
=> Build rpm for continuous-atomic in centos-7

Makefile
RPMs built in the tasks container now fail on rhel-atomic as well, so
build it in the VM.
=> Build rpm for rhel-atomic in centos-7

package.json, src/app.jsx, src/manifest.json, test/check-ostree
Model this after cockpit-packagekit. ostree sends "change" events in
quick succession, and the first replies often don't include an available
update. To avoid flickering between "up to date" and "update available",
debounce the handler for 1s.
Rework the manifest to use a simple /updates path, and preload our page.
Factorize out the releaseName() filter to a separate function, so that
we can re-use it directly from JS.
The test currently only works on fedora-coreos, as RHEL and CentOS
Atomic have a too old cockpit that doesn't support page statuses yet.
=> Set page status for availability of an update

Makefile, test/check-ostree
On the login page the `Reuse password` checkbox was dropped and that
makes all the tests to fail.
See https://github.com/cockpit-project/cockpit/commit/ef97e7e9a28a
=> test: Bump test/common to 228

Makefile
The continuous-atomic image got dropped a month ago [1] due to being
obsolete.
[1] https://github.com/cockpit-project/bots/pull/1178
=> Switch default TEST_OS to fedora-coreos

.github/workflows/npm-update.yml
- Run the job daily, just like cockpituous does (roughly, it was much
more probabilistic). Each run will only create one PR at most, so
with weekly we would miss or drag out important updates.
- Drop verbosity. It was useful for rolling this out, but it's prone to
expose secrets, and not very interesting as a run is rather simple to
reproduce locally.
=> actions: npm-update adjustments

test/vm.install
In the Red Hat internal Cockpit CI we constantly run into docker.io pull
rate limits. Use the already existing quay.io mirror of that image from
the app-sre team.
=> test: Pull nginx image from quay.io

.github/workflows/npm-update.yml
GitHub's base VMs don't automatically refresh package indexes, so it can
happen that one of the package dependencies get out of date and are not
available on the mirrors any more.
Run `apt update` first to ensure that the workflow installs the latest
packages.
Ported from starter-kit commit 8771907002e2
-----
Fixes [last night's failure](https://github.com/cockpit-project/cockpit-ostree/runs/1534717420?check_suite_focus=true)
=> workflows: Fix apt installation in npm-update

Makefile, test/check-ostree, test/vm.install
quay.io/app-sre/nginx became inaccessible.
https://quay.io/repository/bitnami/nginx is public and well maintained,
so use that instead.
----
Fixes [this failure](https://logs.cockpit-project.org/logs/pull-1466-20201215-021903-c5c4036a-fedora-coreos-cockpit-project-cockpit-ostree/log.html)
=> test: Use bitnami nginx container

Makefile, packit.yaml
This is needed for packit to work.
Also reusing `$(TARFILE)` macro.
=> Makefile: Output a path to the generated archive

cockpituous-release
Fedora "master" branches were renamed recently.
Also make rawhide build failures fatal; the package build is so simple
that it really should not fail.
=> tools: Rename Fedora rawhide branch in cockpituous control file

cockpituous-release
bodhi activation for Fedora 34 is today [1]. Drop Fedora 32 instead,
which is soon EOL.
[1] https://fedorapeople.org/groups/schedule/f-34/f-34-key-tasks.html
=> cockpituous: Add Fedora 34, drop Fedora 32

Makefile, packit.yaml
Apply the same memory consumption reduction and tarfile printing fixes
as cockpit-podman recently did.
Also clean up `synced_files`, this should not be necessary any more with
current packit.
=> packit: Fix archive creation

packit.yaml
We enabled copr builds in the packit config for you.
After merging this PR, you are just a few steps away from RPM builds being automatically triggered on your PR's.
It means, that you'll be able to try and play with your change, packaged as an RPM.
What are the next steps?
* Install [Packit-as-a-Service github application](https://github.com/marketplace/packit-as-a-service) in your repo
* In case you are first user, wait for account approval
* Enjoy the built RPMs!
For more info, please:
* check out the documentation: https://packit.dev/docs/
* contact [@packit-service/the-packit-team](https://github.com/orgs/packit-service/teams/the-packit-team)
=> Enable copr builds for packit config

cockpit-ostree.spec.in
We accidentally released cockpit-ostree version 999 into Fedora while
testing the release process and some people have been stuck on that
version ever since.
Add an Epoch so that updates can continue as normal.
=> spec file: add Epoch 1

Makefile, package.json, src/app.jsx, test/check-ostree
moment is deprecated now. Use cockpit's new timeformat library instead,
which wraps date-fns and deals with localization automatically.
This fixes non-localized date/time formatting, as the page forgot to
call moment.locale().
----
There is no visual difference in English:
It just looks different in other languages now due to the previously missing localization.
=> Port from moment to date-fns

test/vm.install
When trying to fetch the branch name out of the booted image, allow for
the new fedora: remote type, in addition to ostree:.
=> test/vm.install: allow new fedora: remote type

Makefile
I visually tested this (as we did a lot of obsolete PF deprecation and such) and it looks fine.
=> Bump test and common cockpit API to 257

.github/deploy-keys.sh, .github/workflows/weblate-sync-po.yml, .github/workflows/weblate-sync-pot.yml, Makefile, po/html2po, po/manifest2po, test/run
This is a bit fiddly to test right now, as the new workflows are not on main yet. I did [create the github env](https://github.com/cockpit-project/cockpit-ostree/settings/environments), and the [weblate repo](https://github.com/cockpit-project/cockpit-ostree-weblate) otherwise looks as expected. In the interest of not jumping through too many hoops, could we merge this, then run the workflows manually, and I sort out possible fallout afterwards? (Then in subsequent PRs, we can easily run the workflows from the fork)
=> Bring back translation updates

Makefile
See https://github.com/cockpit-project/cockpit/commit/c3309b7a560
----
Fixes [this test failure](https://logs.cockpit-project.org/logs/pull-218-20211201-023211-99ab0751-fedora-coreos/log.html) from PR #218 or [the image refresh](https://github.com/cockpit-project/bots/pull/2678)
I visually tested the pkg/lib bump, looks fine.
=> test: Bump test/common API to get along with Cockpit 258 shell

Makefile, src/app.jsx, src/client.js, src/ostree.scss
This is all in comments, including some imported files, except for one function where the variable is changed throughout. I'll comment on that to highlight it below.
=> Fix typos and spelling errors found by codespell

src/app.jsx, test/check-ostree
Move away from the PF3 FontAwesome names in favor of the PF4 icon components.
See https://github.com/cockpit-project/cockpit/commit/85fd223bfc261826cb4c607efb6ef38f11609b47
Fixes #226
=> Move page status icons to PF4

test/check-ostree, test/vm.install
The bitnami image mirrored from dockerhub was removed from quay.io and
as we can't pull from dockerhub due to rate limitting use a different
nginx image. In the future the image should be pulled into the testing
container so tests can run fully offline.
Note, I've attempted to use the smaller lighttpd image but this image does not work well with our tests, the container isn't getting killed with `stop_trivial_httpd`. No Python image seems to be available on quay.io for us to simply use python -m http.server
=> test: switch to new container image

Makefile, test/vm.install
Create the test virtual machine offline now that the coreos image
contains the used nignx container. For rpm-ostree to run offline, invoke
it with --cache-only so it doesn't try to fetch repository data.
=> test: offline image-customize

packit.yaml
As usual, keep supporting the two most recent branched versions.
Also drop Rawhide from our cockpit-preview COPR build: We directly
upload new releases to Rawhide anyway, so this is redundant.
=> packit: Drop Fedora 35, add Fedora 37

Makefile, README.md, cockpit-ostree.spec.in
/usr is package manager territory, and not even writable on OSTree based systems such as Fedora CoreOS or RHEL Edge. Given that we primarily target OSTree, `make install` should do the right thing there.
You can still override this with `make install PREFIX=...`. Use that in the RPM spec file.
---
Motivated by https://bugzilla.redhat.com/show_bug.cgi?id=2126471
=> Install into /usr/local/share/ by default

.github/workflows/npm-update-pf.yml, .github/workflows/npm-update.yml, .github/workflows/weblate-sync-po.yml, .github/workflows/weblate-sync-pot.yml
actions/checkout@v3 uses nodejs 16 as runtime instead of the deprecated nodejs 12 runtime.
=> .github: update checkout action to v3

Makefile, README.md, test/check-ostree, test/vm.install
Fedora 37's rpmspec changed behaviour: `-q` now shows the source RPM
name instead of the binary one. `--srpm` and `--rpms` don't influence
this behaviour any more. So get along with both variants.
---
See #289 for the current test failure.
=> Fix for Fedora 37 task container

cockpit-ostree.spec.in
See https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_1
Also see 9bb49fe1c4d027a37eab61e8a2b187ffef168a2d in cockpit.
=> cockpit-ostree.spec.in: Migrate spec to SPDX license

Makefile, src/index.html, src/ostree.scss, test/check-ostree, test/vm.install
When using offical kickstart the name differs a bit. Also piggybacking small UI fix
=> Fix rhel-edge name and fill background

src/manifest.json
Only show ostree if the system is actually *using* OSTree, by checking for /sysroot/ostree. It sometimes happens that users install cockpit-ostree on classic RPM systems, which "breaks" the "Software Updates" page.
This is a better solution than the current static priorities of packagekit vs. ostree. However, this only works with the Python bridge [1].
Fixes #295
[1] https://github.com/cockpit-project/cockpit/pull/18291
=> manifest: Add condition

Makefile, README.md, package.json, src/remotes.js, src/test-utils.js, src/utils.js, webpack.config.js
Cockpit recently changed to an ESM build system [1]. Bump COCKPIT_REPO_COMMIT to that and follow suit.
Adjust some imports/exports to be ESM conformant.
[1] https://github.com/cockpit-project/cockpit/pull/18366
----
Pretty much identical to https://github.com/cockpit-project/starter-kit/pull/625 except for some extra import fixes.
=> build: Move to a webpack module, generalize bundler language/variable names

test/check-ostree
The previous try to wait for the table to become stable didn't work, since the table appears fully populated in one step.  The unstable part that influences the column widths is the name of the second deployment, which changes from one run to the next.
=> test: Ignore unstable deployment table columns

Makefile, src/client.js
cockpit.defer() has been deprecated for a long time. Replace with    
standard Promise API and chaining.    
There is one instance left which uses the .notify() API. Replacing this    
needs some more work.
=> Port most of src/client.js to standard Promises

.github/workflows/cockpit-lib-update.yml, .github/workflows/npm-update-pf.yml, .github/workflows/npm-update.yml, .github/workflows/weblate-sync-po.yml, .github/workflows/weblate-sync-pot.yml
Like https://github.com/cockpit-project/starter-kit/pull/643 and https://github.com/cockpit-project/cockpit/pull/18668 . The newer ubuntu platform already got tested in cockpit and starter-kit, and most workflows here already had `permissions:`. 
I added `statuses: write`, as the PO workflows have it, too. I'm not sure that we really need it, but it's harmless enough.
I restricted the default token permissions to read-only now.
=> workflows: Update to ubuntu-latest, set explicit permissions

test/check-ostree
https://github.com/cockpit-project/cockpit/commit/14174cf6f6c1a44f17 happened after Cockpit 292 release.
----
This blocks https://github.com/cockpit-project/bots/pull/4811
=> test: Fix PF5 divide version check

test/check-ostree
The first deployment we first wait on the packages and then count, apply this here as well.
Not a huge fan of the code around it, but this should resolve the flake.
=> test: wait before count packages

Makefile
It's not needed to invoke npm, it's also slower then directly invoking `build.js`.
=> Makefile: prefer running build.js directly

Makefile, package.json, src/ostree.scss
This requires a CSS tweak for the "change-repo" button, to stay vertically centered in the toolbar.
[pixel diff review](https://github.com/cockpit-project/pixel-test-reference/compare/81085cab682a0d6b2011763003182ab68dc7e0c5..0358a00c0d21932c9648b06a78060d2e867eac0f)
=> package.json: Update to PatternFly 5 final

src/client.js
This no is no longer used since the switch to PatternFly. Uncovered by coverage!
=> Drop running_method

Makefile, README.md, build.js, test/run
stylelint 16 causes a deadlock/crash in esbuild [1]. There's no movement on that issue, and we want stylelint 16 to be able to support the Browser Baseline 2023.
Follow https://github.com/cockpit-project/cockpit/commit/1a28b31828e and move the linters into test/static-code. This also starts to lint files which are outside of esbuild's realm, such as documentation and examples.
[1] https://github.com/evanw/esbuild/issues/3542
Taken from https://github.com/cockpit-project/starter-kit/commit/15be8835955f8
=> Move eslint/stylelint to static-code tests

test/check-ostree
This can legitimately take a while.
--
Should fix [this flake](https://cockpit-logs.us-east-1.linodeobjects.com/pull-530-20240227-180853-9902a5a3-rhel4edge/log.html#4-1)
=> test: Increase timeout for reset dialog

pyproject.toml
These aren't unused, but discovered/enumerated by `unittest` or `pytest`.
=> lint: Ignore test functions in vulture

src/client.js, src/ostree.jsx, src/utils.js, test/check-ostree
The rpm-ostree API has these in a `container-image-reference` field for
deployments and versions. In the UI we want to show them the same way as
"classic" OSTree repository origins.
Fix `get_default_origin()` to consider the *last* colon-separated
component as the branch name, instead of all but the first. OCI
repositories contain other colons (ate least the schema, and possibly
a registry domain port).
----
On current main, all the "OSTree source" and "Branch" and "Origin" fields are empty. Now they show the OCI repo:
cockpit-ostree now detects and shows the origin, repository, and branch name of [native container repositories](https://coreos.github.io/rpm-ostree/container/).
TODO: screenshot with "real" Fedora source
=> Show OCI container origin

.flake8, pyproject.toml, test/check-ostree
Ruff's preview rules now implements the rules which we used flake8 for.
=> test: enable ruff preview rules

test/vm.install
In some test runs `OstreeOCICase.testBasic` fails on
> Error: name "ostree-registry" is in use: container already exists
This doesn't reproduce locally. These are destructive tests, so the only plausible explanation is that the container was not actually removed on `podman stop` despite the `-rm` option. Clean it up more explicitly.
----
I saw this [fail](https://cockpit-logs.us-east-1.linodeobjects.com/pull-582-b53cbd84-20240424-050816-centos-9-bootc/log.html) [twice](https://cockpit-logs.us-east-1.linodeobjects.com/pull-582-b53cbd84-20240423-204039-centos-9-bootc/log.html) since yesterday, let's see if this helps.
=> test: Explicitly remove ostree-registry container

build.js
In the introduction of the metafile argument accidentally it was added to the watch mode instead of the normal build.
---
Don't hack in the airport lobby :grin:
=> build.js: write metafile in a normal build

.eslintrc.json, build.js, src/deploymentModals.jsx, src/ostree.jsx, src/remotes.js, src/repositoryModals.jsx, src/test-utils.js
This more or less enforces existing practice, but cleans up many places where we've deviated from that.  We sort into these groups:
- 'react', if present, always first
- external (`node_modules/`) imports
- cockpitlib (`pkg/lib/`) imports
- parent (`../`) imports
- sibling (`./`) imports
=> eslint: configure import sorting rules

test/check-ostree
We really should avoid `tbody:nth-child(n)` selectors, as they are so
misleading: Reading that suggests that that this selects the nth
`<tbody>` tag, but that isn't so [1] -- that's what `:nth-of-type(n)` does.
That's why all of the numbers were apparently off by one, as they had to
account for the extra `<thead>` in the parent `<table>`.
[1] https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child
----
This doesn't solve https://github.com/cockpit-project/bots/pull/6630 , but makes the investigation a lot more clear.
=> test: Robustify and clarify deployment selectors

test/check-ostree
All of our currently supported OSes have a newer cockpit-system, and we also don't test rhel4edge any more.
=> test: Drop old superuser indicator code

test/check-ostree
Current rpm-ostreed exits after its configured `IdleExitTimeout` (default one minute), regardless of how many connections it has or when the last request happened [1]. It also doesn't properly unregister from D-Bus when it exists. So there is no way to properly work around that for us: we can neither send it keep-alive pings/requests nor react to `close` messages (not even when we enable the `track: true` option).
The `bootc switch` call in our test is quite expensive and takes around a minute. rpm-ostreed often times out while that's running, so that from then on the UI will never update any more as it does not receive any signals any more.
Hack around that by reloading the page after the call, to get a fresh connection and updated UI.
[1] https://issues.redhat.com/browse/RHEL-49603
--- …
=> test: Hack around rpm-ostreed's unstoppable suicide

Makefile, package.json
See https://github.com/cockpit-project/cockpit/pull/20832
Explicitly add a "glob" devDependency to follow suit with https://github.com/cockpit-project/cockpit/commit/680decc155a It was previously used implicitly through a transient dependency of something else, but our esbuild po-plugin uses it explicitly.
=> test: Move from CDP to BiDi

src/client.js, test/check-ostree
This is a better workaroud for
https://issues.redhat.com/browse/RHEL-49603
than the hack commit e20543c79575e042b284. Revert the latter.
---
I tested this locally with `ExitIdleTimeout=10`. I just don't want to do that in the VM setup, and rather keep the default config.
=> Use rpm-ostree's RegisterClient() method for stopping suicide

test/check-ostree
Works around the flaky RTL test, see also https://ci-weather-cockpit.apps.ocp.cloud.ci.centos.org/tests.html?repo=cockpit-project%2Fcockpit-ostree
=> test: wait for RTL layout changes to settle

cockpit-ostree.spec.in
cockpit-ostree is one of the dependents of rpm-ostree. We are removing i686 buids on this pkg from fedora version 41 and above.
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/1716#issuecomment-2358745869
---
Originally submitted here: https://src.fedoraproject.org/rpms/cockpit-ostree/pull-request/52
=> spec: Do not build on ix86

build.js
Found by eslint-plugin-unicorn.
=> build.js: prefer startsWith over regex with a caret

test/vm.install
The latest Fedora CoreOS image [1] adds the `bootc` package by default,
but it's not actually booted with bootc:
```
No staged image present
Current booted image: localhost/bootc:latest
Image version: stream9.20241108.0 (2024-11-09 22:42:18.512463512 UTC)
Image digest: sha256:7e1298b4888321b4ce4b497a2db0f9786e701cc1435957501049ef80194bba1d
No rollback image present
```
So query for the currently booted bootc image, like `bootc status --help`
suggests.
[1] https://github.com/cockpit-project/bots/pull/7103
=> test: More precise bootc check

package.json
The ostree plugin doesn't use bootstrap anymore since the React/PF4 rewrite in 2020.
=> package.json: drop bootstrap-sass dependency

test/check-ostree
bootc changed the version output in `bootc status` to now quote the version number. This breaks our test which expects an unquoted string.
=> test: obtain bootc booted version from json

test/check-ostree, test/vm.install
New fedora-coreos images will change the branch name from "fedora/x86_64/coreos/testing" to just "testing".
Pixel diffs: https://github.com/cockpit-project/pixel-test-reference/compare/c9a3a3e030b76afa853d2f3e78056af54255b711..f8e6928db5b51c213d53eb0d35c0bc33b799a3a0
=> Updates for new fedora-coreos image

.github/workflows/codeql.yml
There is no reason to stick with Ubuntu 22.04
=> workflows: run codeql workflow on Ubuntu latest

test/check-ostree
This keeps being noisy with each fedora-coreos image, and we keep changing it (last time in #880). With this project being on life support, it's not worth spending lots of time figuring this out.
---
After https://github.com/cockpit-project/bots/pull/7938 it now [happened again](https://cockpit-logs.us-east-1.linodeobjects.com/pull-7975-abba3fcb-20250710-053317-fedora-coreos-cockpit-project-cockpit-ostree/log.html) in https://github.com/cockpit-project/bots/pull/7975 .
=> test: Drop medium layout of "deployment" pixel test
